Demos/App Demo for iOS/App Demo for iOS/AppDelegate.m, Demos/WebView Demo for iOS/WebView Demo for iOS/AppDelegate.m
1Password beta is no longer required to integrate with the 1Password App Extension API. Developers simply need to download 1Password from the App Store to test their integration.
**BEFORE:**
**AFTER:**
=> Replaced the email for beta access alert with a link to get 1Password from the App Store when 1Password is not installed.

Demos/App Demo for iOS/App Demo for iOS/ChangePasswordViewController.m
**Steps to reproduce:**
1. Go the the Change Password view
2. Do not enter any values for the old, new and confirmation passwords.
**Expected behaviour:**
The share sheet should be available because they old password may be too long to type. It will be returned by 1Password after the user changes it in the detail view.
**Actual behaviour:**
We get a validation alert saying that the old and the new password must not be the same. Therefore forcing the user to enter a dummy value in the old password field.
=> Fixed validation problem in ACME where the old password need to be typed when changing the password.

1PasswordExtension.podspec, Demos/App Demo for iOS/App Demo for iOS/Info.plist, Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist, OnePasswordExtension.m
[NEW] Added support for the iPhone 6 and 6 Plus for ACME and ACME Browser.
[NEW] Added support for Carthage in the [add-framework-support](https://github.com/AgileBits/onepassword-app-extension/tree/add-framework-support) branch.
[NEW] Added light cloured assets for the 1Password Button.
[IMPROVED] Updated filling code for the upcoming filling brain in 1Password. (1Password 5.3 betas are required)
[IMPROVED] We now validate that the new password and the old password are not the same when changing the password in ACME.
[IMPROVED] Minimized the scope of some string constants to help prevent "duplicate symbol" linker errors when this code is included more than once in an app (because one or more libraries includes this code).
[FIXED] Fixed problem where passwords containling `\` did not …
=> [RELEASE] 1.1.1

OnePasswordExtension.m
This issue is old the collected page details was never valid for `UIWebViews`. This fix will enable the new filling brain from the 1Password 5.3 betas to work properly.
=> [FIXED] Fixed issue that was causing the 1Password Beta Extension to crash when attempting to fill into UIWebViews in third party apps using.

1PasswordExtension.podspec, Demos/App Demo for iOS/App Demo for iOS/Info.plist, Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist, OnePasswordExtension.m
[FIXED] Fixed issue that was causing the **1Password 5.3 Beta Extension** to crash when attempting to fill into UIWebViews in third party apps using.
=> [RELEASE] 1.1.2

1PasswordExtension.podspec, README.md
This should resolve issue #180
=> [NEW] Added Swift compatibility for CocoaPods 0.36

Demos/App Demo for iOS/App Demo for iOS/Info.plist, Demos/Browser Filling Demo for iOS/Browser Filling Demo for iOS/Info.plist, Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist, OnePasswordExtension.m
[NEW] Added the all new [Fill into Browser capability](https://github.com/AgileBits/onepassword-app-extension#use-case-5-browser-filling-support). This enables the 1Password Extension to show alongside other activities and to fill Credit Cards and Identities into your browser's web views. {#186}
[NEW] Added Swift compatibility for CocoaPods 0.36 or later. {#182}
[IMPROVED] The latest and greatest filling Brain in 1Password 5.3 or later will automatically be used for the [Web View Login](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-login-support) and [Browser filling](https://github.com/AgileBits/onepassword-app-extension#use-case-5-browser-filling-support) capabilities when filling Logins, Credit Cards and Identities. {#171, #172, #178 and #184}
[IMPROVED] …
=> [RELEASE] 1.2

Demos/WebView Demo for iOS/WebView Demo for iOS/WebViewController.m, OnePasswordExtension.m, README.md
"Web View Login Support" -> "Web View Filling Support"
=> More README improvements

Demos/App Demo for iOS Swift/App Demo for iOS Swift/Base.lproj/Main.storyboard, Demos/App Demo for iOS/App Demo for iOS/Base.lproj/Main.storyboard
The sign up button was not appearing so I moved it a bit to the top (I didn't move the hidden textfield of the one time generated password).
=> Update constraints for iPhone screen so the "Sign Up" button is visible

OnePasswordExtension.m, README.md
See the README instructions about [WKWebView support for projects with iOS 7.1 or earler as the Deployment Target](https://github.com/AgileBits/onepassword-app-extension/tree/add-ability-to-enable-wk-webview-for-older-os-versions#wkwebview-support-for-projects-with-ios-71-or-earler-as-the-deployment-target)
This should resolve #212.
=> [NEW] Added ability to use WKWebView when the Deployment Target is iOS 7.1 or earlier

OnePasswordExtension.h, OnePasswordExtension.m
Extension is now audited for nullability, assumes non null for the file as a whole and annotates specific items that are nullable.
should improve usage in Swift
=> Audits extension for nullability

OnePasswordExtension.m
NSLocalizedStringFromTable allows for better organization of the .strings files that are generated when using the 'genstrings' command-line utility. This change results in the creation of a separate file named OnePasswordExtension.strings containing all of the key/value pairs that specifically belong to the 1Password extension library.
References:
1) http://www.objc.io/issues/9-strings/string-localization/
2) https://github.com/AFNetworking/AFNetworking
/to @radazzouz
/cc @olliewagner @trstout
=> Use NSLocalizedStringFromTable instead of NSLocalizedString.

Demos/App Demo for iOS/App Demo for iOS/Info.plist, Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist, README.md
Whitelisted the "org-appextension-feature-password-management" URL scheme when the base SDK is iOS 9.0 or later.
=> Fixed issue where 1Password appeared as not installed if the base SDK was iOS 9.0.

README.md
`MobileCoreServices.framework` is no longer required when the deployment target is iOS 7.1 or earlier. Also updated the screenshot.
=> [IMPROVED] Improved wording in the README.

OnePasswordExtension.h
Currently the completion parameter `error` is not marked as `nullable` in findLoginForURLString.
=> Added missing nullable to findLoginForURLString completion parameter

OnePasswordExtension.m
* Moved `isSystemAppExtensionAPIAvailable` with other private methods.
* No longer using `NSClassFromString(@"NSExtensionItem")`. We now use `[NSExtensionItem class]`.
=> Minor code improvements in `OnePasswordExtension.m`

OnePasswordExtension.m
This should remind developers to make sure that the sender is non-nil on iPad.
=> [IMPROVED] We now throw an exception when the `sender` parameter is `nil` on iPad.

Demos/App Demo for iOS/App Demo for iOS/RegisterViewController.m, OnePasswordExtension.h, OnePasswordExtension.m
This should resolve #233 
1. Making sure that the *1Password App Extension API* builds fine with older versions of Xcode (6.2).
2. Added more nullability annotations to the public methods.
=> More nullability fixes

Demos/App Demo for iOS/App Demo for iOS/ChangePasswordViewController.m, Demos/App Demo for iOS/App Demo for iOS/RegisterViewController.m, OnePasswordExtension.h, README.md
These changes require 1Password for iOS 5.5 or later.
```
[NEW] Added the ability to blacklist unsupported characters when using the password generator options. {#36}
[IMPROVED] Improved the password generator options. {#36}
[FIXED] Fixed an issue where the Password Generator length keys were not honoured in 1Password 5.5. {#35}
```
This should resolve issues #35 and #36
=> Improvements for the password generator options.

Demos/WebView Demo for iOS/WebView Demo for iOS/Base.lproj/Main.storyboard, Demos/WebView Demo for iOS/WebView Demo for iOS/WebViewController.m
Changes in this PR:
1. Use `NSURLComponents` for Google Search in ACME Browser.
2. Make the search bar's keyboardType in ACME browser be web search instead of URL search.
=> [IMPROVED] Improved Google Search in ACME Browser.

OnePasswordExtension.m
Forgot to add nullability for `findLoginIn1PasswordWithURLString` in previous PRs. Now all methods, including the private ones have nullability.
=> [IMPROVED ]Added nullability to `findLoginIn1PasswordWithURLString:`

1PasswordExtension.podspec, Demos/App Demo for iOS/App Demo for iOS/Info.plist, Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist, OnePasswordExtension.h, OnePasswordExtension.m, README.md
[NEW] Added the ability to retrieve the generated One-Time Password from the 1Password Login if available. {#163, #199}
[NEW] Added the ability to specify unsupported  characters when using the password generator options. {#36}
[NEW] Added nullability for improved compatibility with Swift projects. {#218, #241,#245}
[NEW] Our demo apps, **ACME** and **ACME Browser** are now written in [Swift 1.2](https://github.com/AgileBits/onepassword-app-extension/tree/new/swift-demo-apps) and [Swift 2.0](https://github.com/AgileBits/onepassword-app-extension/tree/swift2.0) too. {#101}
[NEW] Added ability to use the WKWebView code when the Deployment Target is iOS 7.1 or earlier. {#214}
[IMPROVED] Simplified [Web View Filling](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-fi …
=> [Release] 1.5

1PasswordExtension.podspec
We should be reached https://twitter.com/1Password instead.
=> Updated the social media URL in the Podspec.

README.md
Replaced `AppExtensionURLStringKey` with `URLString`.
This should resolve #253.
=> [IMPROVED] Clarifying the use of the URL string in the README.

Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist, Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
Forcing the Swift demo apps to portrait mode to match the Objective-C demo apps.
=> [FIXED] Forcing the Swift demo apps to portrait mode.

1PasswordExtension.podspec
if we don’t use « use_frameworks! » in the podfile, we can’t build the
project anymore (impossible to find header file).
=> fix issue with cocoa pods 0.39 and static library.

README.md
Mentioning that SFSafariViewController now works on devices running iOS 9.2 or later. Also fixed a few typos in the README while I was at it.
We should merge this once iOS 9.2 stable is out. This should then resolve #239.
=> [IMPROVED] Updated the README to mention that SFSafariViewController now works on devices running iOS 9.2 or later.

README.md
We now mention that the URL string is required in order to associate the icon with it on our Rich Icons server.
=> [IMPROVED] Improved the instructions for the Rich Icons submission in the Best Practice section.

README.md
=> [IMPROVED] Updated the documentation to mention all the required frameworks to link for projects targeting iOS 7.1 or earlier.

Demos/App Demo for iOS/App Demo for iOS.xcodeproj/project.pbxproj, OnePasswordExtension.h
The extension triggers warnings when compiled with CLANG_WARN_DOCUMENTATION_COMMENTS=true.
This PR fixes the warnings and enables this warning by default (to help avoid this issue in future).
=> Enabling documentation warnings, and fixing HeaderDoc invalid documentation

1PasswordExtension.podspec
=> [IMPROVED] Improved compatibility with CocoaPods 1.0.0.

OnePasswordExtension.m
This should resolve #314. A big :+1: to @hborders!
In ARC we should cast `CFStringRefs` using `(__bridge NSString *)`. Otherwise, it would generate warning when using the `-Wcast-qual` compiler flag.
=> [FIXED] Fixed casting to NSString of CFStringRef constants.

README.md
Fix the urls of the readme badges to display the 1Password info, instead of default AFNetworking
=> Update the metadata badges in the README

Demos/App Demo for iOS Swift/App Demo for iOS Swift/ChangePasswordViewController.swift, Demos/App Demo for iOS Swift/App Demo for iOS Swift/LoginViewController.swift, Demos/App Demo for iOS Swift/App Demo for iOS Swift/RegisterViewController.swift, Demos/App Demo for iOS Swift/App Demo for iOS Swift/ThankYouViewController.swift
Launch ACME Swift (`App Demo for iOS Swift`) on an iPad.
The app should simply run, even if no images are available in `Images.xcassets`. This should and will be addressed separately
Bam! It crashes on launch with the `"fatal error: unexpectedly found nil while unwrapping an Optional value"` error message in the console.
=> [FIXED] Fixed a crash caused by unwrapping an Optional value while running ACME Swift on iPad.

OnePasswordExtension.h, OnePasswordExtension.m
Apple's documentation for [declaring and creating blocks][blockdocs] advocates for naming block types when they are used in multiple places. The current 1Password extension API "spells out" entire block signatures at each use, despite having only three distinct completion block types.
Including `typedef`s for these three block types would significantly reduce line noise across seven method declarations in OnePasswordExtension.h, as well as several more in the corresponding implementation file.
[blockdocs]: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Blocks/Articles/bxDeclaringCreating.html
This branch declares these three types in OnePasswordExtension.h, each with the name pattern `OnePassword<Kind>CompletionBlock`. "Kind" is:
* `Login` for blocks that pass a …
=> Add typedefs for completion blocks

OnePasswordExtension.h
All completion blocks need to be `nonnull`. Otherwise, the 1Password extension cannot reply after it has been completed by the user.
=> [IMPROVED] All the completion blocks from the API are now `nonnull`

Demos/WebView Demo for iOS/WebView Demo for iOS/WebViewController.m
Fixed bug that happened during refactoring in the WebView Demo for iOS
https://github.com/AgileBits/onepassword-app-extension/commit/55e9ed14c583e781150357f64643e4f7f739eae0
`-	if (!navigation) {`
`+	if (navigation != nil) {`
=> fixed refactoring bug in WebView Demo for iOS

Demos/App Demo for iOS Swift/App Demo for iOS Swift/ChangePasswordViewController.swift, Demos/App Demo for iOS Swift/App Demo for iOS Swift/RegisterViewController.swift, Demos/App Demo for iOS/App Demo for iOS/ChangePasswordViewController.m, Demos/App Demo for iOS/App Demo for iOS/RegisterViewController.m, README.md
* "bellow" -> "below"
* "with will" -> "will not"
=> Fix typos in sample code
