- .gitignore
- Demos/1Password Extension Demos.xcworkspace/contents.xcworkspacedata
- Demos/App Demo for iOS/App Demo for iOS.xcodeproj/project.pbxproj
- Demos/App Demo for iOS/App Demo for iOS/AppDelegate.m
- Demos/App Demo for iOS/App Demo for iOS/Base.lproj/Main.storyboard
- Demos/App Demo for iOS/App Demo for iOS/ChangePasswordViewController.m
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/LoginViewController.m
- Demos/App Demo for iOS/App Demo for iOS/RegisterViewController.m
- Demos/WebView Demo for iOS/WebView Demo for iOS.xcodeproj/project.pbxproj
- Demos/WebView Demo for iOS/WebView Demo for iOS/AppDelegate.m
- Demos/WebView Demo for iOS/WebView Demo for iOS/Base.lproj/Main.storyboard
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/WebViewController.m
- Info.plist
- OnePasswordExtension.xcodeproj/project.pbxproj
- OnePasswordExtension.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- OnePasswordExtension.xcodeproj/xcshareddata/xcschemes/OnePasswordExtension.xcscheme
This is equivalent to, and supersedes‚ #151 but instead targets the `add-framework-support` branch.
> Add Xcode project [to `add-framework-support` branch]

- README.md
Much like the CocoaPods note I’ve added a note on Carthage support.
As per discussion in #148 and #151.
**Depends on #152 before it can be merged!**
> Add notes about Carthage to the README

- Demos/App Demo for iOS/App Demo for iOS/ChangePasswordViewController.m
- Demos/App Demo for iOS/App Demo for iOS/LoginViewController.m
- Demos/App Demo for iOS/App Demo for iOS/RegisterViewController.m
- OnePasswordExtension.m
- README.md
The weak/strong self dances are unnecessary here, see [this Stack Overflow answer][1] to understand why.
[1]: http://stackoverflow.com/questions/19018456/ios-blocks-and-strong-weak-references-to-self/19018633#19018633
> Remove weak/strong self dances

- OnePasswordExtension.m
This PR should resolve #160, because I basically made the same change that @JGiola made in his initial commit in PR #160.
Cheers buddy!
> Fixed issue with some shadowed error variables.

- 1PasswordExtension.podspec
Last thing to do before releasing version `1.2`
> Updated the podspec's version number

- README.md
Also made some minor changes such as making the distinction between the "1Password extension" and the "1Password App Extension API"
> Added instructions to run  the App Extension API from master in the README

- Demos/App Demo for iOS/App Demo for iOS/Base.lproj/Main.storyboard
- Demos/App Demo for iOS/App Demo for iOS/LoginViewController.m
- OnePasswordExtension.h
To test this feature you must use 1Password for iOS `5.4.1.BETA-1` or later.
This PR should resolve #163.
> Added the ability to retrieve the generated One-Time Password from the Login if available.

- README.md
Removed beta references, including our Twitter account.
> Updated wording in the README

- OnePasswordExtension.h
Replaced `the iDevice` with `iDevice`.
> Updated the in-code documentation

- Demos/App Demo for iOS/App Demo for iOS/AppDelegate.m
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/LoginViewController.m
- Demos/WebView Demo for iOS/WebView Demo for iOS/AppDelegate.m
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/WebViewController.m
Anticipating iOS 9 deprecations.
> [IMPROVED] Better compatibility with iOS 9.

- Demos/WebView Demo for iOS/WebView Demo for iOS.xcodeproj/project.pbxproj
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/welcome.html
> [IMPROVED] ACME Browser is now a Universal app.

- Demos/App Demo for iOS/App Demo for iOS/AppDelegate.h
- Demos/WebView Demo for iOS/WebView Demo for iOS/AppDelegate.h
Reverted the changes from PR #249 to address the warnings in the debug
console.
Nice catch @paulbruneau :thumbsup:
> Reverted the changes from PR #249

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[NEW] Added Swift demo apps. {#101 #257}
[NEW] Added newsletter sign up in the README. {#252}
[IMPROVED] Improved compatibility with Xcode 7.
[IMPROVED] Clarifying the use of the URL string in the README. {#253, #254}
[FIXED] Fixed the social media URL for CocoaPods. {#247}
```
> [RELEASE] 1.6

- OnePasswordExtension.h
- OnePasswordExtension.m
Also made some other tiny changes to the header documentation. This should resolve #262.
> [IMPROVED] Improved the header documentation.

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[IMPROVED] Improved the header documentation. {#262, #263}
[IMPROVED] Updated the in-code documentation for the improved `Change Password` capability. {#264}
```
> [RELEASE] 1.6.1

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[IMPROVED] Updated the Javascript code for Web View Filling. {#260, #261}
```
> [Release] 1.6.2

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[IMPROVED] Improved compatibility with CocoaPods 0.39.0. {#268, #270}
```
> [Release] 1.6.3

- OnePasswordExtension.m
found by our I18n translators. :smiley:
> correct typo

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[IMPROVED] Improved the compatibility of the Demo apps with Xcode 7.1. {#272}
[FIXED] Fixed typo in error message. {#274}
```
> [Release] 1.6.4

- README.md
We now have 23 KB README :wink:
> Updated the README file size.

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[NEW] Added documentation to the Wiki. Thank you so much for reaching and for contributing. Feel free to open issues requesting Wiki documentation.
[IMPROVED] Improved compatibility with CocoaPods 1.0.0. {#302}
[IMPROVED] Updated the Javascript code for Web View Filling. {#303}
[IMPROVED] Improved the instructions for the Rich Icons submission in the Best Practice section. {#290}
[IMPROVED] Updated the documentation to mention all the required frameworks to link for projects targeting iOS 7.1 or earlier. {#294, #296}
[IMPROVED] Improved the header documentation. {#298}
[IMPROVED] Listing all the required frameworks in the podspec file. {#297}
[IMPROVED] Removed extra new lines for a clearer code and README. {#293}
[IMPROVED] Removed usless semicolons from Swift code. {#295}
[FIXED] …
```
> [Release] 1.8

- README.md
A huge thank you to @Dershowitz011 :+1:
> [NEW] Added metadata badges to the README.

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[NEW] Added metadata badges to the README. {#319. #321}
[IMPROVED] Updated the Javascript code for Web View Filling. {#316}
[FIXED] Fixed casting to NSString of CFStringRef constants. {#317}
```
> [Release] 1.8.1

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
```
[IMPROVED] Updated the Javascript code for Web View Filling. {#324}
[FIXED] Fixed a crash caused by unwrapping an Optional value while running ACME Swift on iPad. {#323}
```
> [Release] 1.8.2

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
[NEW] Added typedefs for completion blocks for more flexibility. {#339}
[IMPROVED] Updated the Javascript code for Web View Filling. {#335}
[IMPROVED] All the completion blocks from the API are now `nonnull`. {#341}
[FIXED] Fixed minor typo in the documentation. {#340}
> [RELEASE] 1.8.3

- Demos/App Demo for iOS Swift/App Demo for iOS Swift.xcodeproj/project.pbxproj
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift.xcodeproj/project.pbxproj
> Fixed build errors on Xcode 8 for the Swift sample apps

- 1PasswordExtension.podspec
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/Info.plist
- Demos/App Demo for iOS/App Demo for iOS/Info.plist
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/Info.plist
- Demos/WebView Demo for iOS/WebView Demo for iOS/Info.plist
- OnePasswordExtension.m
- README.md
[FIXED] Fixed build errors on Xcode 8 for the Swift sample apps {#346}
> [RELEASE] 1.8.4

- Demos/App Demo for iOS Swift/App Demo for iOS Swift/ChangePasswordViewController.swift
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/LoginViewController.swift
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/RegisterViewController.swift
- Demos/App Demo for iOS Swift/App Demo for iOS Swift/ThankYouViewController.swift
- Demos/WebView Demo for iOS Swift/WebView Demo for iOS Swift/WebViewController.swift
This PR takes Kyles changes and adds to them with more Swift code style updates. An noted in Kyles PR (#393), the Objective-C app extension code can do a lot more to be inclusive of Swift. It's missing many useful annotations that would make the Swift code simpler.
> modernize swift style
